### ISSUE TITLE
add a bash completion

### ISSUE THREAD

**Issue by drzraf** [coddingtonbear/timebook#4]
Would be nice to have a bash-completion so that:
``t in <tab>`` could complete with the suggestions from ``t list``.

**Comment by coddingtonbear** [comment]
Sure would, wouldn't it? Could you file a pull request adding that feature?

**Comment by drzraf** [comment]
> Sure would, wouldn't it? Could you file a pull request adding that
> feature?

I've little time for this, but why not.

* If you want a "self-contained" completion, then I won't do this myself.
It would mean having a:
``t complete`` command, which, according to args, generate the list of
completion (timebook already has all the logic to do it).
Eg: ``t complete --line=xxx --point=yyy``
generates the completions for line "xxx" when cursor is at position yyy.


* The other, simpler way, is to do a minimal bash script, that needs to be
installed (eg: ~/.bash_completion.d/completions/t) which does the most
basic completion (run ``t list`` when previous argument is ``in|switch``
for example)


If even in the long run, you prefer the second case, I can do it easily

**Comment by coddingtonbear** [comment]
Oh, I think either is totally fine -- whichever solves your problem for you most elegantly.

**Comment by drzraf** [comment]
cf pr #5

**Comment by coddingtonbear** [comment]
Awesome; thanks for submitting that PR, @drzraf!
