### ISSUE TITLE
Is it available as a pip package?

### ISSUE THREAD

**Issue by vonpupp** [coddingtonbear/timebook#6]
Hello,

Your project seems to be a fork of another project on bitbucket which is on [published] on pypi. I stumbled on this project since I am looking for a timesheet for taskwarrior.

I was wondering if your project is (or will be) published on pypi?

Thank you.

[published]: https://pypi.python.org/pypi/timebook/1.2.0

**Comment by coddingtonbear** [comment]
This is only a fork of the official Timebook package (which is [itself available on Pypi](https://pypi.python.org/pypi/timebook/1.2.0)).  Given that this fork was made mostly just to satisfy idiosyncratic quirks of how I myself wanted to track my time a few years ago, and that even I no longer use this package for time tracking, I'm afraid I have no plans of distributing this package.  You're welcome to use it, though, of course, but by doing so, you're entering an only-barely-maintained wilderness of long-forgotten code.
